version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BackendDependencies"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l6r53guce7o"
s3_prefix = "BackendDependencies"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"

