AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
    Function:
        MemorySize: 3008
        Timeout: 900
        Environment:
            Variables:
                CASSANDRA_USERNAME:
                    Fn::Sub: "${CassandraUsername}"
                CASSANDRA_PASSWORD:
                    Fn::Sub: "${CassandraPassword}"
                CASSANDRA_HOST:
                    Fn::Sub: "${CassandraHost}"
                CASSANDRA_PORT:
                    Fn::Sub: "${CassandraPort}"
                CASSANDRA_LOCAL_DC:
                    Fn::Sub: "${CassandraLocalDC}"
                CASSANDRA_KEYSPACE_NAME:
                    Fn::Sub: "${CassandraKeyspaceName}"
                POSTGRESQL_USERNAME:
                    Fn::Sub: "${PostgreSQLUsername}"
                POSTGRESQL_PASSWORD:
                    Fn::Sub: "${PostgreSQLPassword}"
                POSTGRESQL_HOST:
                    Fn::Sub: "${PostgreSQLHost}"
                POSTGRESQL_PORT:
                    Fn::Sub: "${PostgreSQLPort}"
                POSTGRESQL_DB_NAME:
                    Fn::Sub: "${PostgreSQLDBName}"
Parameters:
    EnvironmentName:
        Type: String
    CassandraUsername:
        Type: String
    CassandraPassword:
        Type: String
    CassandraHost:
        Type: String
    CassandraPort:
        Type: String
    CassandraLocalDC:
        Type: String
    CassandraKeyspaceName:
        Type: String
    PostgreSQLUsername:
        Type: String
    PostgreSQLPassword:
        Type: String
    PostgreSQLHost:
        Type: String
    PostgreSQLPort:
        Type: String
    PostgreSQLDBName:
        Type: String
Resources:
    Databases:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName:
                Fn::Sub: "${EnvironmentName}Databases"
            ContentUri: src/aws_lambda_layers/archives/databases.zip
            CompatibleRuntimes:
                - python3.8
            LicenseInfo: MIT
            RetentionPolicy: Retain
    Utils:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName:
                Fn::Sub: "${EnvironmentName}Utils"
            ContentUri: src/aws_lambda_layers/archives/utils.zip
            CompatibleRuntimes:
                - python3.8
            LicenseInfo: MIT
            RetentionPolicy: Retain
Outputs:
    Databases:
        Value:
            Ref: Databases
        Export:
            Name:
                Fn::Sub: "${AWS::StackName}:${EnvironmentName}Databases"
    Utils:
        Value:
            Ref: Utils
        Export:
            Name:
                Fn::Sub: "${AWS::StackName}:${EnvironmentName}Utils"