AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
    EnvironmentName:
        Type: String
        Default: Test
Resources:
    Requests:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName:
                Fn::Sub: "${EnvironmentName}Requests"
            ContentUri: src/aws_lambda_layers/archives/requests.zip
            CompatibleRuntimes:
                - python3.8
            LicenseInfo: MIT
            RetentionPolicy: Retain
    Databases:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName:
                Fn::Sub: "${EnvironmentName}Databases"
            ContentUri: src/aws_lambda_layers/archives/databases.zip
            CompatibleRuntimes:
                - python3.8
            LicenseInfo: MIT
            RetentionPolicy: Retain
    Utils:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName:
                Fn::Sub: "${EnvironmentName}Utils"
            ContentUri: src/aws_lambda_layers/archives/utils.zip
            CompatibleRuntimes:
                - python3.8
            LicenseInfo: MIT
            RetentionPolicy: Retain
Outputs:
    Requests:
        Value:
            Ref: Requests
        Export:
            Name:
                Fn::Sub: "${AWS::StackName}:${EnvironmentName}Requests"
    Databases:
        Value:
            Ref: Databases
        Export:
            Name:
                Fn::Sub: "${AWS::StackName}:${EnvironmentName}Databases"
    Utils:
        Value:
            Ref: Utils
        Export:
            Name:
                Fn::Sub: "${AWS::StackName}:${EnvironmentName}Utils"