AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
    EnvironmentName:
        Type: String
Resources:
    Databases:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName:
                Fn::Sub: "${EnvironmentName}Databases"
            ContentUri: src/aws_lambda_layers/archives/databases.zip
            CompatibleRuntimes:
                - python3.8
            LicenseInfo: MIT
            RetentionPolicy: Retain
    Utils:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName:
                Fn::Sub: "${EnvironmentName}Utils"
            ContentUri: src/aws_lambda_layers/archives/utils.zip
            CompatibleRuntimes:
                - python3.8
            LicenseInfo: MIT
            RetentionPolicy: Retain
    Requests:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName:
                Fn::Sub: "${EnvironmentName}Requests"
            ContentUri: src/aws_lambda_layers/archives/requests.zip
            CompatibleRuntimes:
                - python3.8
            LicenseInfo: MIT
            RetentionPolicy: Retain