#!/bin/bash

mkdir -p "python/lib/python3.8/site-packages"
pip install cassandra-driver==3.24.0 aws-psycopg2==1.2.1 --target "python/lib/python3.8/site-packages"
cp "src/aws_lambda_layers/databases.py" "python/lib/python3.8/site-packages"
cp "src/aws_lambda_layers/AmazonRootCA1.pem" "python/lib/python3.8/site-packages"
zip -r "src/aws_lambda_layers/archives/databases.zip" "python/lib/python3.8/site-packages"
rm -rf "python"

mkdir -p "python/lib/python3.8/site-packages"
cp "src/aws_lambda_layers/utils.py" "python/lib/python3.8/site-packages"
zip -r "src/aws_lambda_layers/archives/utils.zip" "python/lib/python3.8/site-packages"
rm -rf "python"

mkdir -p "python/lib/python3.8/site-packages"
pip install requests==2.24.0 --target "python/lib/python3.8/site-packages"
zip -r "src/aws_lambda_layers/archives/requests.zip" "python/lib/python3.8/site-packages"
rm -rf "python"

mkdir -p "python/lib/python3.8/site-packages"
pip install Pillow==8.1.0 --target "python/lib/python3.8/site-packages"
zip -r "src/aws_lambda_layers/archives/Pillow.zip" "python/lib/python3.8/site-packages"
rm -rf "python"